name: i18next
description: A localization formatter based on the i18next standard. It is not yet a fully i18n tool only the formatting itself.
version: 0.4.1
repository: https://github.com/nubank/i18next
homepage: https://github.com/nubank/i18next

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

flutter:
